version: '3.6'
services:
  app:
    build:
      context: ./app
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    env_file: app/config.env
  redis:
    image: redis:3.2-alpine
    restart: always
    volumes:
      - redis_data:/data
volumes:
  redis_data:
